package com.dujian.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUsername(String username) {
		set("username", username);
	}
	
	public String getUsername() {
		return getStr("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}
	
	public String getPassword() {
		return getStr("password");
	}

	public void setAge(Integer age) {
		set("age", age);
	}
	
	public Integer getAge() {
		return getInt("age");
	}

	public void setSex(Integer sex) {
		set("sex", sex);
	}
	
	public Integer getSex() {
		return getInt("sex");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}
	
	public String getPhone() {
		return getStr("phone");
	}

}
